In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [2]:
reviews=['nice food',
        'amazing restaurant',
        'too good',
        'just loved it',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'need improvement']

In [3]:
sentiment=np.array([1,1,1,1,1,0,0,0,0,0])

In [4]:
one_hot('nice food',30)

[20, 20]

In [5]:
vocab_size=30
encoded=[one_hot(i,vocab_size) for i in reviews]
encoded  #The size of the array is three in some cases because of the three words in the element of the array

[[20, 20],
 [26, 9],
 [18, 29],
 [21, 29, 7],
 [5, 7, 26],
 [27, 20],
 [11, 7, 3],
 [11, 8],
 [11, 8],
 [23, 21]]

In [6]:
max_length=3
padded_review=pad_sequences(encoded,maxlen=max_length,padding='post')
padded_review  #To make the size of all the array we need to pad the elements of the array(you can set the max length to which size you want the vector)

array([[20, 20,  0],
       [26,  9,  0],
       [18, 29,  0],
       [21, 29,  7],
       [ 5,  7, 26],
       [27, 20,  0],
       [11,  7,  3],
       [11,  8,  0],
       [11,  8,  0],
       [23, 21,  0]])

In [7]:
model=keras.Sequential()

In [8]:
vector_size=5
model.add(keras.layers.Embedding(vocab_size,vector_size,input_length=max_length,name='embedding'))

C:\Users\Kale Ji\AppData\Roaming\Python\Python311\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [9]:
model.add(keras.layers.Flatten())

In [10]:
model.add(keras.layers.Dense(1,activation='sigmoid'))

In [11]:
model.compile(optimizer='adam',
             loss='binary_crossentropy',
             metrics=['accuracy'])

In [12]:
X=padded_review
y=sentiment

In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [15]:
model.fit(X,y,epochs=30)

Epoch 1/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.7000 - loss: 0.6775
Epoch 2/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.7000 - loss: 0.6756
Epoch 3/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.7000 - loss: 0.6738
Epoch 4/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.8000 - loss: 0.6720
Epoch 5/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.9000 - loss: 0.6702
Epoch 6/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.9000 - loss: 0.6683
Epoch 7/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.9000 - loss: 0.6665
Epoch 8/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.9000 - loss: 0.6647
Epoch 9/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.9000 - loss: 0.6628
Epoch 10/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.9000 - loss: 0.6610
Epoch 11/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 1.0000 - loss: 0.6591
Epoch 12/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 1.0000 - loss: 0.6573
E

In [16]:
weights=model.get_layer('embedding').get_weights()[0]

In [17]:
len(weights)

30

In [18]:
weights

array([[-0.0228158 , -0.05581994,  0.00316663, -0.03256231, -0.01359256],
       [-0.00388402,  0.00882416,  0.04253249, -0.01456218, -0.0306343 ],
       [-0.03648789,  0.01311703,  0.03442612,  0.02055902,  0.04989478],
       [-0.03942184, -0.05390422,  0.04833186, -0.06476816, -0.0894686 ],
       [ 0.04813189,  0.01786704,  0.02442613,  0.02730538,  0.00514917],
       [-0.07823233, -0.06409079,  0.02252761, -0.06506031,  0.00402932],
       [-0.04717684,  0.01034629, -0.02671546,  0.01719509,  0.01633463],
       [ 0.05629541,  0.05816994, -0.03857898,  0.02085299,  0.00195235],
       [-0.05070057,  0.07829855,  0.03730189,  0.08079112, -0.01935612],
       [-0.00828026, -0.07933609, -0.04251448, -0.00162211,  0.06031927],
       [ 0.0047071 ,  0.01362509, -0.04367098,  0.03127239,  0.04850218],
       [ 0.08225854,  0.09714232, -0.10838352,  0.08719129, -0.02363446],
       [ 0.02822288,  0.04610166, -0.0269744 , -0.01385087, -0.00113388],
       [-0.0202736 , -0.01637218,  0.0

In [19]:
weights[26]

array([ 0.05344049, -0.01730904, -0.00167314, -0.01753824,  0.04407908],
      dtype=float32)

In [20]:
weights[29]

array([ 0.01869958, -0.08663604, -0.05627731, -0.04393831,  0.07510927],
      dtype=float32)

In [21]:
weights[27]

array([ 0.03981886,  0.01589353, -0.00995263,  0.02157107, -0.06662602],
      dtype=float32)

In [23]:
loss,accuracy=model.evaluate(padded_review,sentiment)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 1.0000 - loss: 0.6204


In [24]:
accuracy*100

100.0

In [25]:
18/1.5

12.0

In [26]:
100/18

5.555555555555555

In [27]:
18*3

54