In [1]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv(r"C:\Users\Kale Ji\Downloads\IMDB-Dataset.csv")
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [5]:
df.review[0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fa

In [6]:
df.sentiment.value_counts()

positive    25000
negative    25000
Name: sentiment, dtype: int64

In [7]:
df.describe()

review sentiment
count                                               50000     50000
unique                                              49582         2
top     Loved today's show!!! It was a variety and not...  positive
freq                                                    5     25000

In [9]:
df.sentiment.replace({'positive':1,'negative':0},inplace=True)

In [10]:
df.head()

review  sentiment
0  One of the other reviewers has mentioned that ...          1
1  A wonderful little production. <br /><br />The...          1
2  I thought this was a wonderful way to spend ti...          1
3  Basically there's a family where a little boy ...          0
4  Petter Mattei's "Love in the Time of Money" is...          1

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.review,df.sentiment,test_size=0.2)

In [12]:
X_train.shape

(40000,)

In [14]:
X_train.values

array(['I never thought I see a movie worse than "Lisa Picard Is Famous", but this came pretty close. As repeated often throughout the comments, it was predictable; five minutes into the movie you know it will be a stranded at the alter outcome. This movie painfully references/rips off everything from "Something about Mary" to "Revenge of the Pink Panther". Writer Greg Glienna (Meet the Parents) needs some new material.<br /><br />The only twist is the deranged boyfriend/police officer pursued by internal affairs, but even that opportunity is wasted. Lots of setting shots of the Seattle Space Needle necessary to disguise the obvious Canadian shooting locale. Some of the worst driving in the car scenes with almost no effort to disguise the fact that the car is being pulled through town on a trailer. Geez, at least turn the wheel or put the brakes on once in a while. Selma Blair is inert and the short haircut a crime. $3M to Jason Lee, for what? Guess it beats skateboarding!<br /><br />S

In [13]:
X_test.shape

(10000,)

In [23]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=3,stop_words='english')
X_train_count=cv.fit_transform(X_train.values)

In [24]:
X_train_count.toarray()[:2]

array([[4, 0, 4],
       [0, 0, 3]], dtype=int64)

In [25]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(X_train_count,y_train)

MultinomialNB()

In [32]:
review=['This was an awesome movie with flight scenes that were incredibly realistic! I have seen it multiple times and it has kept my attention throughout every time. I myself am a big fan of the Air Force and love to watch any movie where I can get a glimpse of an F-16 flying']
review_count=cv.fit_transform(review)
model.predict(review_count)

array([1], dtype=int64)

In [33]:
X_test_count=cv.fit_transform(X_test.values)

In [34]:
model.score(X_test_count,y_test)

0.5428

In [35]:
import spacy

In [36]:
nlp=spacy.load('en_core_web_sm')

In [37]:
def preprocess(text):
    d=nlp(text)
    n=[i.text for i in d if not i.is_stop and not i.is_punct]
    return " ".join(n)

In [38]:
preprocess(df.review[0])

'reviewers mentioned watching 1 Oz episode hooked right exactly happened me.<br /><br />The thing struck Oz brutality unflinching scenes violence set right word Trust faint hearted timid pulls punches regards drugs sex violence hardcore classic use word.<br /><br />It called OZ nickname given Oswald Maximum Security State Penitentary focuses mainly Emerald City experimental section prison cells glass fronts face inwards privacy high agenda Em City home Aryans Muslims gangstas Latinos Christians Italians Irish scuffles death stares dodgy dealings shady agreements far away.<br /><br />I main appeal fact goes shows dare Forget pretty pictures painted mainstream audiences forget charm forget romance OZ mess episode saw struck nasty surreal ready watched developed taste Oz got accustomed high levels graphic violence violence injustice crooked guards sold nickel inmates kill order away mannered middle class inmates turned prison bitches lack street skills prison experience Watching Oz comfor

In [39]:
df.review[0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fa

In [40]:
df.review=df.review.apply(preprocess)

In [41]:
df.review[2]

'thought wonderful way spend time hot summer weekend sitting air conditioned theater watching light hearted comedy plot simplistic dialogue witty characters likable bread suspected serial killer disappointed realize Match Point 2 Risk Addiction thought proof Woody Allen fully control style grown love.<br /><br />This laughed Woody comedies years dare decade impressed Scarlet Johanson managed tone sexy image jumped right average spirited young woman.<br /><br />This crown jewel career wittier Devil Wears Prada interesting Superman great comedy friends'

In [42]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.review,df.sentiment,test_size=0.2)

In [51]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=3,stop_words='english')
X_train_count=cv.fit_transform(X_train.values)

In [52]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(X_train_count,y_train)

MultinomialNB()

In [53]:
X_test_count=cv.fit_transform(X_test)

In [54]:
model.score(X_test_count,y_test)

0.5404

In [60]:
X_train_count.shape

(40000, 3)

In [61]:
y_train.shape

(40000,)

In [121]:
import tensorflow as tf
from tensorflow import keras
model=keras.Sequential([
    keras.layers.Flatten(),
    keras.layers.Dense(100,activation='relu'),
    keras.layers.Dense(10,activation='relu'),
    keras.layers.Dense(1,activation='sigmoid')
])
# model=tf.keras.Model(inputs=[X_train_count],outputs=[1])

In [115]:
model.compile(optimizer='adam',
             loss='categorical_crossentropy',
             metrics=['accuracy'])

In [116]:
X_train_count.toarray()[:3]

array([[20,  5,  1],
       [12,  3,  1],
       [ 0,  0,  1]], dtype=int64)

In [117]:
X_train_count

<40000x3 sparse matrix of type '<class 'numpy.int64'>'
	with 70077 stored elements in Compressed Sparse Row format>

In [118]:
X_train_count=X_train_count.reshape(-1,)

ValueError: matrix shape must be two-dimensional

In [113]:
model.fit(X_train_count,y_train,epochs=10)

Epoch 1/10


ValueError: Arguments `target` and `output` must have the same shape. Received: target.shape=(32, 1), output.shape=(32, 2)